
syntax on
set co=120
set lines=41
set t_Co=256

" get rid of menu
set guioptions-=m

" get rid of toolbar
set guioptions-=T

if has("gui_win32")
    set guifont=Consolas:h10:cANSI
    set winaltkeys=menu
    " autoselect clipboard
    set guioptions+=a

elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h14

else
    set guifont=Inconsolata\ 12
endif
