
# From oh-my-zsh zshrc template
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git debian pip python tmux virtualenvwrapper)

source $ZSH/oh-my-zsh.sh
source `which virtualenvwrapper.sh`

bindkey -v
bindkey '^R' history-incremental-search-backward
bindkey '^?' backward-delete-char

unsetopt correctall

# Run tmux/screen on shell login
[[ $- != *i* ]] && return
[[ $TERM != screen* ]] && exec tmux -2

# alias chrome="google-chrome --incognito"
# alias ll='ls -l'
# alias la='ls -la'
alias vi='gvim -v'
alias vim='gvim -v'
alias df='df -h'
# alias w3m='w3m -T text/html'
# alias xm='xmodmap $HOME/.Xmodmap'
alias bc='bc -l'
# alias pdf='epdfview'
alias bibref='java -jar ~/bin/JabRef.jar&'
alias optipng='optipng -o7' # always use max optimization

# User specific environment and startup programs

alias encrypt='openssl enc -aes-256-ecb -e -a -salt -in'
alias decrypt='openssl enc -aes-256-ecb -d -a -salt -in'
